DSWBD/04.CadUserWeb/ProjetoEduardo/src/java/br/com/eduardo/model/Eduardo.java
package br.com.eduardo.model;

import java.util.Date;

/**
 *
 * @author eduardo
 */
public class Eduardo {

    private long eduardocpf;
    private Date eduardodatacadastro;
    private String eduardonome;
    private String eduardoendereco;
    private String eduardoemail;
    private String eduardocelular;
    private char eduardosexo;
    private boolean eduardostatus;

    public long getEduardocpf() {
        return eduardocpf;
    }
    
    public String getEduardocpfformat() {
        String pre = String.format("%011d", eduardocpf);
        
        return String.format(
                "%s.%s.%s-%s", 
                pre.substring(0, 3),
                pre.substring(3, 6),
                pre.substring(6, 9),
                pre.substring(9));
    }

    public void setEduardocpf(long eduardocpf) {
        this.eduardocpf = eduardocpf;
    }

    public Date getEduardodatacadastro() {
        return eduardodatacadastro;
    }

    public void setEduardodatacadastro(Date eduardodatacadastro) {
        this.eduardodatacadastro = eduardodatacadastro;
    }

    public String getEduardonome() {
        return eduardonome;
    }

    public void setEduardonome(String eduardonome) {
        this.eduardonome = eduardonome;
    }

    public String getEduardoendereco() {
        return eduardoendereco;
    }

    public void setEduardoendereco(String eduardoendereco) {
        this.eduardoendereco = eduardoendereco;
    }

    public String getEduardoemail() {
        return eduardoemail;
    }

    public void setEduardoemail(String eduardoemail) {
        this.eduardoemail = eduardoemail;
    }

    public String getEduardocelular() {
        return eduardocelular;
    }

    public void setEduardocelular(String eduardocelular) {
        this.eduardocelular = eduardocelular;
    }

    public char getEduardosexo() {
        return eduardosexo;
    }

    public void setEduardosexo(char eduardosexo) {
        this.eduardosexo = eduardosexo;
    }

    public boolean getEduardostatus() {
        return eduardostatus;
    }
    
    public String getEduardostatusdescricao() {
        return (eduardostatus)?"Ativo":"Inativo";
    }

    public void setEduardostatus(boolean eduardostatus) {
        this.eduardostatus = eduardostatus;
    }

}

DSWBD/04.CadUserWeb/ProjetoEduardo/src/java/br/com/eduardo/bll/EduardoController.java
package br.com.eduardo.bll;

import br.com.eduardo.dal.EduardoDAO;
import br.com.eduardo.util.DatabaseException;
import br.com.eduardo.model.Eduardo;
import java.io.IOException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author eduardo
 */
@WebServlet(name = "EduardoController", urlPatterns = {"/EduardoController"})
public class EduardoController extends HttpServlet {

    private static final String INSERT_OR_EDIT = "/eduardo.jsp";
    private static final String LIST = "/listEduardo.jsp";
    private final EduardoDAO dao;

    public EduardoController() {
        super();
        dao = new EduardoDAO();
    }

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String forward;
        String action = request.getParameter("action");

        if (action.equals("delete")) {
            long eduardocpf = Long.parseLong(request.getParameter("eduardocpf"));
            try {
                Eduardo obj = new Eduardo();
                obj.setEduardocpf(eduardocpf);
                dao.delete(obj);
                request.setAttribute("alert", "Usuário excluído com sucesso.");
            } catch (DatabaseException ex) {
                request.setAttribute("alert", "Erro ao excluir usuário");
                Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
            }

            forward = LIST;
            try {
                request.setAttribute("eduardos", dao.getAll());
            } catch (DatabaseException ex) {
                Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (action.equals("edit")) {

            forward = INSERT_OR_EDIT;
            long eduardocpf = Long.parseLong(request.getParameter("eduardocpf"));
            try {
                Eduardo eduardo = dao.retrieve(eduardocpf);
                request.setAttribute("eduardo", eduardo);
                request.setAttribute("title", "Editar Usuário");
                request.setAttribute("action", "update");
            } catch (DatabaseException ex) {
                request.setAttribute("alert", "Erro ao buscar dados para edição");
            }

        } else if (action.equals("insert")) {

            forward = INSERT_OR_EDIT;
            request.setAttribute("action", "insert");
            request.setAttribute("title", "Inserir Usuário");

        } else if (action.equals("list")) {

            forward = LIST;
            try {
                request.setAttribute("eduardos", dao.getAll());
            } catch (DatabaseException ex) {
                Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            forward = LIST;
        }

        RequestDispatcher view = request.getRequestDispatcher(forward);
        view.forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        String action = request.getParameter("action");

        if (action.equals("insert")) {
            Eduardo eduardo = new Eduardo();

            eduardo.setEduardocpf(Long.parseLong(request.getParameter("eduardocpf")));
            eduardo.setEduardodatacadastro(new GregorianCalendar().getTime());
            eduardo.setEduardonome(request.getParameter("eduardonome"));
            eduardo.setEduardoendereco(request.getParameter("eduardoendereco"));
            eduardo.setEduardoemail(request.getParameter("eduardoemail"));
            eduardo.setEduardocelular(request.getParameter("eduardocelular"));
            eduardo.setEduardosexo(request.getParameter("eduardosexo").charAt(0));
            eduardo.setEduardostatus(request.getParameter("eduardostatus").equals("true"));

            try {
                dao.create(eduardo);
                request.setAttribute("alert", "Usuário cadastrado com sucesso.");
            } catch (DatabaseException ex) {
                request.setAttribute("alert", "Erro ao cadastrar usuário.");
                Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (action.equals("update")) {
            try {
                Eduardo eduardo = dao.retrieve(Long.parseLong(request.getParameter("eduardocpf")));

                eduardo.setEduardonome(request.getParameter("eduardonome"));
                eduardo.setEduardoendereco(request.getParameter("eduardoendereco"));
                eduardo.setEduardoemail(request.getParameter("eduardoemail"));
                eduardo.setEduardocelular(request.getParameter("eduardocelular"));
                eduardo.setEduardosexo(request.getParameter("eduardosexo").charAt(0));
                eduardo.setEduardostatus(request.getParameter("eduardostatus").equals("true"));

                dao.update(eduardo);
                request.setAttribute("alert", "Usuário atualizado com sucesso.");
            } catch (DatabaseException ex) {
                request.setAttribute("alert", "Erro ao atualizar usuário.");
                Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        RequestDispatcher view = request.getRequestDispatcher(LIST);
        try {
            request.setAttribute("eduardos", dao.getAll());
        } catch (DatabaseException ex) {
            Logger.getLogger(EduardoController.class.getName()).log(Level.SEVERE, null, ex);
        }
        view.forward(request, response);
    }
}

DSWBD/04.CadUserWeb/ProjetoEduardo/web/eduardo.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link type="text/css" href="css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" />
        <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui-1.8.18.custom.min.js"></script>
        <script type="text/javascript" src="js/scripts.js"></script>
        <title><c:out value="${title}"/></title>
    </head>
    <body>
        <!--        <script>
                    $(function () {
                        $('input[name=dob]').datepicker();
                    });
                </script>-->
        <form method="POST" action='EduardoController' name="frmAddEduardo">
            <input type="hidden" name="action" value="<c:out value="${action}" />">
            <table>
                <tr>
                    <td>CPF:</td>
                    <td><input type="text" name="eduardocpf"  value="<c:out value="${eduardo.eduardocpf}" />" <c:if test = "${action == 'update'}">readonly="readonly"</c:if>/></td>
                    </tr>
                    <tr>
                        <td>Nome:</td>
                        <td><input type="text" name="eduardonome" value="<c:out value="${eduardo.eduardonome}" />"/></td>
                </tr>
                <tr>
                    <td>Endereço:</td>
                    <td><input type="text" name="eduardoendereco" value="<c:out value="${eduardo.eduardoendereco}" />"/></td>
                </tr>
                <tr>
                    <td>E-mail:</td>
                    <td><input type="text" name="eduardoemail" value="<c:out value="${eduardo.eduardoemail}" />"/></td>
                </tr>
                <tr>
                    <td>Celular:</td>
                    <td><input type="text" name="eduardocelular" value="<c:out value="${eduardo.eduardocelular}" />"/></td>
                </tr>
                <tr>
                    <td>Sexo:</td>
                    <td>
                        <input type="radio" name="eduardosexo" <c:if test = "${eduardo.eduardosexo.toString() == 'M'}">checked</c:if> value="M">Masculino
                        <input type="radio" name="eduardosexo" <c:if test = "${eduardo.eduardosexo.toString() == 'F'}">checked</c:if> value="F">Feminino
                        <input type="radio" name="eduardosexo" <c:if test = "${eduardo.eduardosexo.toString() == 'O'}">checked</c:if> value="O">Outro
                        </td>
                    </tr>
                    <tr>
                        <td>Status:</td>
                        <td>
                            <input type="radio" name="eduardostatus" <c:if test = "${eduardo.eduardostatus == true}">checked</c:if> value="true">Ativo
                            <input type="radio" name="eduardostatus" <c:if test = "${eduardo.eduardostatus == false}">checked</c:if> value="false">Inativo
                    </td>
                </tr>
                <tr>
                    <td></td><td><input type="submit" value="Enviar" /></td>
                </tr>
            </table>
        </form>
    </body>
</html>

DSWBD/04.CadUserWeb/ProjetoEduardo/web/index.jsp
<%-- 
    Document   : index
    Created on : 29/08/2017, 20:07:57
    Author     : eduardo
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Página Principal</title>
    </head>
    <body>
        <jsp:forward page="/EduardoController?action=list" />
    </body>
</html>

DSWBD/04.CadUserWeb/ProjetoEduardo/web/listEduardo.jsp
<%@page import="java.util.List"%>
<%@page import="br.com.eduardo.model.Eduardo"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="./css/styles.css" type="text/css">
        <script type="text/javascript" src="js/scripts.js"></script>
        <title>Mostrar Usuários</title>
    </head>
    <body>
        <table border="1" cellspacing="0">
            <thead>
                <tr>
                    <th>CPF</th>
                    <th>Nome</th>
                    <th>Endereço</th>
                    <th>E-mail</th>
                    <th>Celular</th>
                    <th>Sexo</th>
                    <th>Status</th>
                    <th>Data de Cadastro</th>
                    <th colspan=2>Ação</th>
                </tr>
            </thead>
            <tbody>
                <c:if test = "${eduardos.size() < 1}">
                    <tr><td colspan="9"><p align="center"><i>Nenhum registro encontrado</i></p></td></tr>
                </c:if>

                <c:forEach items="${eduardos}" var="eduardo">
                    <tr>
                        <td><c:out value="${eduardo.eduardocpfformat}" /></td>
                        <td><c:out value="${eduardo.eduardonome}" /></td>
                        <td><c:out value="${eduardo.eduardoendereco}" /></td>
                        <td><c:out value="${eduardo.eduardoemail}" /></td>
                        <td><c:out value="${eduardo.eduardocelular}" /></td>
                        <td>
                            <c:if test = "${eduardo.eduardosexo.toString() == 'M'}">Masculino</c:if>
                            <c:if test = "${eduardo.eduardosexo.toString() == 'F'}">Feminino</c:if>
                            <c:if test = "${eduardo.eduardosexo.toString() == 'O'}">Outro</c:if>
                            </td>
                            <td>
                            <c:if test = "${eduardo.eduardostatus == true}">Ativo</c:if>
                            <c:if test = "${eduardo.eduardostatus == false}">Inativo</c:if>
                            </td>
                            <td><fmt:formatDate pattern="dd/MM/yyyy" value="${eduardo.eduardodatacadastro}" /></td>
                        <td><a href="EduardoController?action=edit&eduardocpf=<c:out value="${eduardo.eduardocpf}"/>">Editar</a></td>
                        <td><a href="EduardoController?action=delete&eduardocpf=<c:out value="${eduardo.eduardocpf}"/>" onclick="return questiona('Você tem certeza que deseja excluir o usuário?')">Excluir</a></td>
                    </tr>
                </c:forEach>
            </tbody>
        </table>
        <p><a href="EduardoController?action=insert">Adicionar</a></p>
    </body>
    <c:if test = "${alert != null}">
        <script type="text/javascript">
            alert('<c:out value="${alert}"/>');
        </script>
    </c:if>
</html>